
language: cpp
sudo: required
dist: trusty

install:
  # Steps copied from the rust-sdl2 project.
  - wget https://www.libsdl.org/release/SDL2-2.0.4.tar.gz -O sdl2.tar.gz
  - tar xzf sdl2.tar.gz
  - pushd SDL2-2.0.4 && ./configure && make && sudo make install && popd

matrix:
  include:

  - os: linux
    compiler: gcc
    env: COMPILER=g++-7
    addons:
      apt:
        sources: 
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-5.0
        packages:
          - g++-7
          - clang-5.0
          - libopenal-dev

  - os: linux
    compiler: clang
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-5.0
        packages:
          - g++-7
          - clang-5.0
          - libopenal-dev

  - os: osx
    compiler: clang
    osx_image: xcode10.1

script:

  - cmake -DCMAKE_CXX_COMPILER=$COMPILER . && make
  - ./bin/unittest
