
language: cpp
sudo: required
dist: bionic

install:
  # Steps copied from the rust-sdl2 project.
  - wget https://www.libsdl.org/release/SDL2-2.0.10.tar.gz -O sdl2.tar.gz
  - tar xzf sdl2.tar.gz
  - pushd SDL2-2.0.10 && ./configure && make && sudo make install && popd

matrix:
  include:

  - os: linux
    compiler: gcc
    addons:
      apt:
        sources: 
          - ubuntu-toolchain-r-test
        packages:
          - libgl1-mesa-dev
          - libopenal-dev

  - os: linux
    compiler: clang
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - libgl1-mesa-dev
          - libopenal-dev


# Disabled until Travis CI supports newer xcode images, im using std::any and it is not fully supported yet. 
#  - os: osx
#    compiler: clang
#    osx_image: xcode10.1

script:

  - cmake -DCMAKE_CXX_COMPILER=$COMPILER . && make
  - ./bin/unittest
