
language: cpp
sudo: required
dist: trusty

matrix:
  include:

#  - os: linux
#    compiler: gcc
#    env: COMPILER=g++-4.9
#    addons:
#      apt:
#        sources: 
#          - ubuntu-toolchain-r-test
#        packages:
#          - g++-4.9
#          - libsdl2-dev

  - os: linux
    compiler: clang
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-5.0
        packages:
          - g++-6
          - clang-5.0
          - libsdl2-dev
          - libopenal-dev

script:

  - cmake -DCMAKE_CXX_COMPILER=$COMPILER . && make